version: "3"

services:
  datasci-traffy-report-count-prediction:
    build: .
    container_name: datasci-traffy-report-count-prediction
    restart: always
    environment:
      - EXTRA_ARGS=--reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
